steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    git clone https://github.com/AnnieBem/base-npm.git
    ls -l
    cd base-npm && git checkout Build_Optimization
    cp src/App/Webapp/package.json /workspce/base-npm/.
    cp src/App/Webapp/vueapp/package.json /workspace/base-npm/vue_package.json

steps:
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'gcr.io/my-first-project/base-npm', '.']